### PR TITLE
Mobile version

### PR DESCRIPTION
**Pull request by jorgevrgs**
Added to this request:

- Projects section
- About section

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
Hi @jorgevrgs , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors. Please fix your linters  and re-submit

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by jorgevrgs** [comment]
> Hi @jorgevrgs ,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that has linter errors. Please fix your linters and re-submit
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

There is an error on GitHub actions related to permissions for Webhint. However, other reviewers have validated the code because it is a well-known issue today.

**Comment by jorgevrgs** [comment]
> > > Hi @jorgevrgs ,
> > > While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> > > ## Invalid Code Review Request
> > > You have submitted a project, that has linter errors. Please fix your linters and re-submit
> > > Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray
> > > Cheers and Happy coding!clapclapclap
> > > Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> > > **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> > > _Invalid Code Review Request **does not count** into the code reviews limit._
> > 
> > 
> > There is an error on GitHub actions related to permissions for Webhint. However, other reviewers have validated the code because it is a well-known issue today.
> 
> * I wasn't aware of that. I apologize!

I sent a message for that on the request. I sent a new request review.

**Comment by jorgevrgs** [comment]
I Included the test locally to point out the GitHub action error:


Screen Shot 2021-10-21 at 5 40 23 PM

**Review by Ghiftee — APPROVED** [review]
## STATUS: APPROVED ♻️♻️
Hi @jorgevrgs , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

**Pull request merged**
